name: Build Version Tag

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get versions
        id: versions
        run: .github/scripts/version/get_versions.sh

      - name: Set all version tags
        if: ${{ steps.versions.outputs.TAG_VERSION == '' }}
        run: .github/scripts/version/set_version_tags.sh
          
      - name: Set current version tag
        if: ${{ steps.versions.outputs.IS_VERSION_UPDATED == 'true' }}
        run: 
          tag_name="v${{ steps.versions.outputs.VERSION }}"
          git tag -a $tag_name -m "version ${{ steps.versions.outputs.VERSION }}"
          git push origin $tag_name
