name: Check Version Updated

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get versions
        id: versions
        run: .github/scripts/version/get_versions.sh

      - name: Check version updated
        if: ${{ steps.versions.outputs.IS_VERSION_UPDATED == 'false' }}
        run: exit 1
