name: Delete Version Tags

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete version tags
        run: .github/scripts/version/delete_version_tags.sh
